[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "DS4GFpse2WfQztzucAAtk7NakqhT5bBnRUMsHWSu9CwZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
